import { GoogleGenAI, Modality } from "@google/genai";

const base64ToData = (base64String: string): string => {
  return base64String.split(',')[1];
};

export const generateCostumeImage = async (base64Image: string, pokemonName: string): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set. Please set it in your environment.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const imagePart = {
    inlineData: {
      data: base64ToData(base64Image),
      mimeType: 'image/jpeg',
    },
  };

  const textPart = {
    text: `Generate a photorealistic image of this person wearing a cheap, homemade, and slightly silly Halloween costume of the pokemon ${pokemonName}.`,
  };

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [imagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:image/png;base64,${base64ImageBytes}`;
      }
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate image. The model may have refused the request due to safety settings.");
  }


  throw new Error("No image was generated by the API.");
};
